# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

top = '..'

def build(bld):
    bld.program(target='../unit-tests',
                name='unit-tests',
                source=bld.path.ant_glob('**/*.cpp'),
                use='ndn-svs',
                install_path=None)
